spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: localhost
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: minseok19950727@gmail.com
    password: fcsvhikgghrclszd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
jwt:
  expmini: 5
  salt: kmstokenandjybtokenloveyouyayaiwillgonaverandkakao
  REFRESH_TOKEN_VALIDATION_SECOND: 1500000
  TOKEN_VALIDATION_SECOND : 5000



