spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password:

jwt:
  expmini: 5
  salt: kmstokenandjybtokenloveyouyayaiwillgonaverandkakao
  REFRESH_TOKEN_VALIDATION_SECOND: 1500000
  TOKEN_VALIDATION_SECOND : 5000



