name: Python deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "**.py"

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      
      # 전송할 파일을 담을 디렉토리 생성
    - name: Make Directory for deliver
      run: mkdir pydeploy
      
      
    # main python 파일 넘기기
    - name: Copy python file
      run: cp ./pycode/main.py ./pydeploy
      
    # crolling py 넘기기
    
    - name: Copy crolling file 
      run: cp ./pycode/crolling.py ./pydeploy
      
    # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp ./pycode/appspec.yml ./pydeploy

      
    # 압축파일 형태로 전달
    - name: Make zip file
      run: zip -r -qq -j ./pythonserver.zip ./pydeploy
      working-directory: ${{env.working-directory}}     
      
    # S3 Bucket으로 copy
    - name: Deliver to AWS S3
      env:
        AWS_S3_BUCKET: ${{secrets.AWS_PRODUCTION_BUCKET_NAME}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
      run: |
        aws s3 cp --region ap-northeast-2 --acl private ./pythonserver.zip s3://$AWS_S3_BUCKET

      
      
    # 배포
    - name: CodeDeploy
      env:
        AWS_S3_BUCKET: ${{secrets.AWS_PRODUCTION_BUCKET_NAME}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
          --application-name coinapp \
          --deployment-group-name coin-deploy-group \
          --s3-location bucket=$AWS_S3_BUCKET,key=pythonserver.zip,bundleType=zip \
          --region ap-northeast-2
 
